<a href="https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Mở trong Colab"/></a> 

[Xem Mã Nguồn](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb) | [Xem Slide](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/slides/00_pytorch_and_deep_learning_fundamentals.pdf) | [Xem Video Hướng Dẫn](https://youtu.be/Z_ikDlimN6A?t=76)

# 00. Các Khái Niệm Cơ Bản Về PyTorch

## PyTorch là gì?

[PyTorch](https://pytorch.org/) là một framework mã nguồn mở cho học máy (machine learning) và học sâu (deep learning).

## PyTorch có thể được sử dụng để làm gì?

PyTorch cho phép bạn thao tác và xử lý dữ liệu cũng như viết các thuật toán học máy bằng mã Python.

## Ai sử dụng PyTorch?

Nhiều công ty công nghệ lớn nhất thế giới như [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla và Microsoft cũng như các công ty nghiên cứu trí tuệ nhân tạo như [OpenAI sử dụng PyTorch](https://openai.com/blog/openai-pytorch/) để hỗ trợ nghiên cứu và đưa học máy vào các sản phẩm của họ.

![pytorch being used across industry and research](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

Ví dụ, Andrej Karpathy (giám đốc AI tại Tesla) đã có một vài bài nói chuyện ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) về cách Tesla sử dụng PyTorch để vận hành các mô hình thị giác máy tính (computer vision) tự lái của họ.

PyTorch cũng được sử dụng trong các ngành công nghiệp khác như nông nghiệp để [hỗ trợ thị giác máy tính trên máy kéo](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## Tại sao nên sử dụng PyTorch?

Các nhà nghiên cứu học máy rất thích sử dụng PyTorch. Và tính đến tháng 2 năm 2022, PyTorch là [framework học sâu được sử dụng nhiều nhất trên Papers With Code](https://paperswithcode.com/trends), một trang web theo dõi các tài liệu nghiên cứu học máy và các kho mã nguồn đính kèm với chúng.

PyTorch cũng giúp xử lý nhiều vấn đề ở hậu trường như tăng tốc GPU (giúp mã của bạn chạy nhanh hơn).

Vì vậy, bạn có thể tập trung vào việc thao tác dữ liệu và viết các thuật toán, còn PyTorch sẽ đảm bảo chúng chạy nhanh.

Và nếu các công ty như Tesla và Meta (Facebook) sử dụng nó để xây dựng các mô hình mà họ triển khai nhằm vận hành hàng trăm ứng dụng, lái hàng ngàn chiếc xe và phân phối nội dung tới hàng tỷ người, thì rõ ràng nó cũng rất mạnh mẽ trên mặt trận phát triển.

## Chúng ta sẽ đề cập những gì trong module này

Khóa học này được chia thành các phần khác nhau (các notebook).

Mỗi notebook đề cập đến các ý tưởng và khái niệm quan trọng trong PyTorch.

Các notebook tiếp theo xây dựng dựa trên kiến thức từ notebook trước đó (đánh số bắt đầu từ 00, 01, 02 và tiếp tục đến bất cứ đâu nó kết thúc).

Notebook này đề cập đến khối xây dựng cơ bản của học máy và học sâu, đó là tensor.

Cụ thể, chúng ta sẽ đề cập đến:

| **Chủ đề** | **Nội dung** |
| ----- | ----- |
| **Giới thiệu về tensors** | Tensors là khối xây dựng cơ bản của tất cả các hệ thống học máy và học sâu. |
| **Tạo tensors** | Tensors có thể biểu diễn hầu như mọi loại dữ liệu (hình ảnh, từ ngữ, bảng số). |
| **Lấy thông tin từ tensors** | Nếu bạn có thể đưa thông tin vào một tensor, bạn cũng sẽ muốn lấy nó ra. |
| **Thao tác với tensors** | Các thuật toán học máy (như mạng nơ-ron - neural networks) liên quan đến việc thao tác với tensors theo nhiều cách khác nhau như cộng, nhân, kết hợp. | 
| **Xử lý hình dạng (shape) của tensor** | Một trong những vấn đề phổ biến nhất trong học máy là xử lý sự không khớp hình dạng (cố gắng trộn các tensor sai hình dạng với các tensor khác). |
| **Chỉ mục (Indexing) trên tensors** | Nếu bạn đã từng lập chỉ mục trên một danh sách Python hoặc mảng NumPy, nó rất giống với tensors, ngoại trừ việc chúng có thể có nhiều chiều (dimensions) hơn nhiều. |
| **Trộn lẫn tensors PyTorch và NumPy** | PyTorch chơi với tensors ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy thích mảng ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) đôi khi bạn sẽ muốn trộn lẫn và kết hợp chúng. | 
| **Tính tái lập (Reproducibility)** | Học máy mang tính thử nghiệm rất cao và vì nó sử dụng nhiều sự *ngẫu nhiên* để hoạt động, đôi khi bạn sẽ muốn sự *ngẫu nhiên* đó bớt ngẫu nhiên hơn. |
| **Chạy tensors trên GPU** | GPUs (Graphics Processing Units - Bộ xử lý đồ họa) làm cho mã của bạn chạy nhanh hơn, PyTorch giúp việc chạy mã của bạn trên GPUs trở nên dễ dàng. |

## Bạn có thể nhận trợ giúp ở đâu?

Tất cả tài liệu cho khóa học này [được lưu trên GitHub](https://github.com/mrdbourke/pytorch-deep-learning).

Và nếu bạn gặp rắc rối, bạn có thể đặt câu hỏi trên [trang Discussions](https://github.com/mrdbourke/pytorch-deep-learning/discussions) ở đó.

Ngoài ra còn có [diễn đàn dành cho nhà phát triển PyTorch](https://discuss.pytorch.org/), một nơi rất hữu ích cho mọi thứ liên quan đến PyTorch.

## Nhập (Importing) PyTorch

> **Lưu ý:** Trước khi chạy bất kỳ mã nào trong notebook này, bạn nên xem qua [các bước thiết lập PyTorch](https://pytorch.org/get-started/locally/). 
>
> Tuy nhiên, **nếu bạn đang chạy trên Google Colab**, mọi thứ sẽ hoạt động (Google Colab đi kèm với PyTorch và các thư viện khác đã được cài đặt sẵn).

Hãy bắt đầu bằng cách nhập PyTorch và kiểm tra phiên bản chúng ta đang sử dụng.

In [1]:
import torch
torch.__version__

'2.2.2'

Tuyệt vời, có vẻ như chúng ta đã có PyTorch 1.10.0+. 

Điều này có nghĩa là nếu bạn đang xem qua các tài liệu này, bạn sẽ thấy tính tương thích cao nhất với PyTorch 1.10.0+, tuy nhiên nếu số phiên bản của bạn cao hơn thế nhiều, bạn có thể nhận thấy một số điểm không nhất quán. 

Và nếu bạn có bất kỳ vấn đề nào, vui lòng đăng lên [trang GitHub Discussions](https://github.com/mrdbourke/pytorch-deep-learning/discussions) của khóa học.

## Giới thiệu về tensors 

Bây giờ chúng ta đã nhập PyTorch, đã đến lúc tìm hiểu về tensors.

Tensors là khối xây dựng cơ bản của học máy.

Công việc của chúng là biểu diễn dữ liệu theo cách số học.

Ví dụ, bạn có thể biểu diễn một hình ảnh dưới dạng một tensor có hình dạng (shape) `[3, 224, 224]` nghĩa là `[colour_channels, height, width]`, vì hình ảnh có `3` kênh màu (đỏ, xanh lá, xanh dương), chiều cao (height) là `224` pixel và chiều rộng (width) là `224` pixel.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

Trong ngôn ngữ của tensor (ngôn ngữ được sử dụng để mô tả tensors), tensor này sẽ có ba chiều (dimensions), một chiều cho `colour_channels` (kênh màu), `height` (chiều cao) và `width` (chiều rộng).

Nhưng chúng ta đang đi hơi xa rồi.

Hãy tìm hiểu thêm về tensors bằng cách code chúng.

### Tạo tensors 

PyTorch rất yêu thích tensors. Đến mức có cả một trang tài liệu dành riêng cho lớp [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html).

Bài tập về nhà đầu tiên của bạn là [đọc qua tài liệu về `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) trong 10 phút. Nhưng bạn có thể làm điều đó sau.

Hãy code nào.

Điều đầu tiên chúng ta sẽ tạo là một **vô hướng (scalar)**.

Một vô hướng là một số duy nhất và trong ngôn ngữ của tensor, nó là một tensor không chiều (zero dimension).

> **Lưu ý:** Đó là một xu hướng cho khóa học này. Chúng ta sẽ tập trung vào việc viết code cụ thể. Nhưng tôi cũng sẽ thường xuyên giao các bài tập liên quan đến việc đọc và làm quen với tài liệu PyTorch. Bởi vì rốt cuộc, sau khi hoàn thành khóa học này, chắc chắn bạn sẽ muốn học thêm. Và tài liệu là nơi bạn sẽ thường xuyên tìm đến.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Thấy cách đoạn code trên in ra `tensor(7)` không?

Điều đó có nghĩa là mặc dù `scalar` là một số duy nhất, nó thuộc loại `torch.Tensor`.

Chúng ta có thể kiểm tra số chiều của một tensor bằng cách sử dụng thuộc tính `ndim`.

In [3]:
scalar.ndim

0

Sẽ thế nào nếu chúng ta muốn lấy số từ tensor ra?

Nói cách khác, chuyển nó từ `torch.Tensor` thành một số nguyên (integer) Python?

Để làm điều này, chúng ta có thể sử dụng phương thức `item()`.

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Được rồi, bây giờ chúng ta hãy xem một **vectơ (vector)**.

Một vectơ là một tensor một chiều nhưng có thể chứa nhiều số.

Nói cách khác, bạn có thể có một vectơ `[3, 2]` để mô tả `[số phòng ngủ, số phòng tắm]` trong ngôi nhà của bạn. Hoặc bạn có thể có `[3, 2, 2]` để mô tả `[số phòng ngủ, số phòng tắm, bãi đỗ xe]` trong ngôi nhà của bạn.

Xu hướng quan trọng ở đây là một vectơ rất linh hoạt trong những gì nó có thể biểu diễn (tương tự với tensors).

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Tuyệt vời, `vector` bây giờ chứa hai số 7, con số yêu thích của tôi.

Bạn nghĩ nó sẽ có bao nhiêu chiều?

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

Hmm, thật kỳ lạ, `vector` chứa hai số nhưng chỉ có một chiều duy nhất.

Tôi sẽ bật mí cho bạn một mẹo.

Bạn có thể biết số chiều của một tensor trong PyTorch bằng số lượng dấu ngoặc vuông ở bên ngoài (`[`) và bạn chỉ cần đếm một bên.

`vector` có bao nhiêu dấu ngoặc vuông?

Một khái niệm quan trọng khác đối với tensors là thuộc tính `shape` (hình dạng) của chúng. Hình dạng cho bạn biết cách các phần tử bên trong chúng được sắp xếp.

Hãy kiểm tra hình dạng của `vector`.

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

Đoạn code trên trả về `torch.Size([2])` có nghĩa là vectơ của chúng ta có hình dạng là `[2]`. Điều này là do hai phần tử chúng ta đã đặt bên trong dấu ngoặc vuông (`[7, 7]`).

Bây giờ chúng ta hãy xem một **ma trận (matrix)**.

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Chà! Nhiều số hơn! Các ma trận cũng linh hoạt như các vectơ, ngoại trừ việc chúng có thêm một chiều.

In [9]:
# Check number of dimensions
MATRIX.ndim

2

`MATRIX` có hai chiều (bạn có đếm số dấu ngoặc vuông ở một bên không?).

Bạn nghĩ nó sẽ có `shape` (hình dạng) như thế nào?

In [10]:
MATRIX.shape

torch.Size([2, 2])

Chúng ta nhận được đầu ra `torch.Size([2, 2])` vì `MATRIX` có chiều sâu là 2 phần tử và chiều rộng là 2 phần tử.

Còn việc chúng ta tạo một **tensor** thì sao?

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Wow! Thật là một tensor đẹp mắt.

Tôi muốn nhấn mạnh rằng các tensor có thể biểu diễn hầu như mọi thứ.

Tensor chúng ta vừa tạo có thể là doanh số bán hàng của một cửa hàng bít tết và bơ hạnh nhân (hai trong số những món ăn yêu thích của tôi).

![a simple tensor in google sheets showing day of week, steak sales and almond butter sales](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

Bạn nghĩ nó có bao nhiêu chiều? (gợi ý: sử dụng mẹo đếm dấu ngoặc vuông)

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

Và hình dạng của nó thì sao?

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Được rồi, nó trả về `torch.Size([1, 3, 3])`.

Các chiều đi từ ngoài vào trong.

Điều đó có nghĩa là có 1 chiều kích thước 3 x 3.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Lưu ý:** Bạn có thể nhận thấy tôi sử dụng các chữ cái viết thường cho `scalar` (vô hướng) và `vector` (vectơ) và chữ cái viết hoa cho `MATRIX` (ma trận) và `TENSOR` (tensor). Tôi cố ý làm vậy. Trong thực tế, bạn sẽ thường thấy vô hướng và vectơ được ký hiệu bằng chữ viết thường như `y` hoặc `a`. Và ma trận cùng với tensor được ký hiệu bằng chữ viết hoa như `X` hoặc `W`.
>
> Bạn cũng có thể nhận thấy các tên gọi ma trận và tensor được sử dụng thay thế cho nhau. Điều này rất phổ biến. Vì trong PyTorch, bạn thường xuyên làm việc với các `torch.Tensor` (do đó có tên gọi tensor), tuy nhiên, hình dạng và số chiều của những gì bên trong sẽ quyết định chính xác nó là gì.

Hãy tóm tắt lại.

| Tên | Nó là gì? | Số chiều | Chữ thường hay hoa (thông thường/ví dụ) |
| ----- | ----- | ----- | ----- |
| **vô hướng (scalar)** | một số duy nhất | 0 | Thường (`a`) | 
| **vectơ (vector)** | một số có hướng (ví dụ: tốc độ gió kèm theo hướng) nhưng cũng có thể có nhiều số khác | 1 | Thường (`y`) |
| **ma trận (matrix)** | một mảng các số 2 chiều | 2 | Hoa (`Q`) |
| **tensor** | một mảng các số n-chiều | có thể là bất kỳ số nào, tensor 0-chiều là vô hướng, tensor 1-chiều là vectơ | Hoa (`X`) | 

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors (Tensors ngẫu nhiên)

Chúng ta đã xác định rằng các tensors đại diện cho một số dạng dữ liệu.

Và các mô hình học máy, chẳng hạn như mạng nơ-ron (neural networks), sẽ thao tác và tìm kiếm các khuôn mẫu bên trong các tensors.

Tuy nhiên, khi xây dựng các mô hình học máy với PyTorch, rất hiếm khi bạn tạo các tensors thủ công (như những gì chúng ta vừa làm).

Thay vào đó, một mô hình học máy thường bắt đầu với các tensors chứa các con số ngẫu nhiên rất lớn, sau đó điều chỉnh các con số này khi nó xử lý dữ liệu để biểu diễn dữ liệu tốt hơn.

Về cơ bản:

`Bắt đầu với các số ngẫu nhiên -> xem dữ liệu -> cập nhật các số ngẫu nhiên -> xem dữ liệu -> cập nhật các số ngẫu nhiên...`

Là một nhà khoa học dữ liệu, bạn có thể xác định cách mô hình học máy bắt đầu (khởi tạo - initialization), xem xét dữ liệu (biểu diễn - representation) và cập nhật (tối ưu hóa - optimization) các số ngẫu nhiên của nó.

Chúng ta sẽ thực hành các bước này sau.

Hiện tại, hãy xem cách tạo một tensor với các số ngẫu nhiên.

Chúng ta có thể làm điều này bằng cách sử dụng [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) và truyền vào tham số `size`.

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2488, 0.7382, 0.2682, 0.8594],
         [0.9544, 0.7761, 0.6800, 0.1087],
         [0.5898, 0.8385, 0.1554, 0.3773]]),
 torch.float32)

Tính linh hoạt của `torch.rand()` nằm ở chỗ chúng ta có thể điều chỉnh `size` thành bất cứ thứ gì chúng ta muốn.

Ví dụ, giả sử bạn muốn một tensor ngẫu nhiên với hình dạng phổ biến của hình ảnh là `[224, 224, 3]` (`[chiều_cao, chiều_rộng, kênh_màu]`).

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones (Toàn số 0 và toàn số 1)

Đôi khi bạn sẽ chỉ muốn điền vào tensors các số 0 hoặc số 1.

Điều này thường xảy ra khi che giấu (masking - như việc che một số giá trị trong tensor bằng số không để mô hình biết rằng không cần học chúng).

Hãy tạo một tensor toàn số 0 bằng hàm [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Chúng ta có thể làm điều tương tự để tạo một tensor toàn số 1, ngoại trừ việc sử dụng [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html).

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Tạo một phạm vi (range) và các tensors tương tự (tensors like)

Đôi khi bạn có thể muốn một dải số, chẳng hạn như 1 đến 10 hoặc 0 đến 100.

Bạn có thể sử dụng `torch.arange(start, end, step)` để làm điều đó.

Trong đó:
* `start` = điểm bắt đầu của dải (ví dụ: 0)
* `end` = điểm kết thúc của dải (ví dụ: 10)
* `step` = số bước nhảy giữa mỗi giá trị (ví dụ: 1)

> **Lưu ý:** Trong Python, bạn có thể sử dụng `range()` để tạo một dải. Tuy nhiên trong PyTorch, `torch.range()` đã bị phản đối (deprecated) và có thể hiển thị lỗi trong tương lai.

In [18]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_1201490/193451495.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Đôi khi bạn có thể muốn một tensor thuộc một loại nhất định với hình dạng (shape) giống với một tensor khác.

Ví dụ, một tensor toàn số 0 có cùng hình dạng với một tensor trước đó. 

Để làm như vậy, bạn có thể sử dụng [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) hoặc [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) lần lượt trả về một tensor chứa toàn số không hoặc số một với cùng hình dạng như `input`.

In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Các kiểu dữ liệu của tensor

Có rất nhiều [kiểu dữ liệu tensor khác nhau có sẵn trong PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Một số kiểu dành riêng cho CPU và một số kiểu tốt hơn cho GPU.

Việc làm quen để biết cái nào là cái nào có thể mất một chút thời gian.

Nói chung, nếu bạn thấy `torch.cuda` ở bất kỳ đâu, tensor đó đang được sử dụng cho GPU (vì các GPU của Nvidia sử dụng một bộ công cụ tính toán gọi là CUDA).

Kiểu phổ biến nhất (và nói chung là mặc định) là `torch.float32` hoặc `torch.float`.

Được gọi là "số thực dấu phẩy động 32-bit" (32-bit floating point).

Nhưng cũng có số thực dấu phẩy động 16-bit (`torch.float16` hoặc `torch.half`) và số thực dấu phẩy động 64-bit (`torch.float64` hoặc `torch.double`).

Và để làm mọi thứ rối thêm một chút, còn có các số nguyên (integers) 8-bit, 16-bit, 32-bit và 64-bit.

Cộng thêm nhiều thứ khác nữa!

> **Lưu ý:** Số nguyên (integer) là một số tròn phẳng như `7`, trong khi số thực (float) có phần thập phân `7.0`.

Lý do cho tất cả những điều này liên quan đến **độ chính xác trong điện toán (precision in computing)**.

Độ chính xác là mức độ chi tiết được sử dụng để mô tả một con số.

Giá trị độ chính xác càng cao (8, 16, 32), thì càng có nhiều chi tiết và do đó càng tốn nhiều dữ liệu để biểu diễn một con số.

Điều này rất quan trọng trong học sâu và tính toán số học vì bạn đang thực hiện rất nhiều phép toán; bạn càng có nhiều chi tiết để tính toán, bạn càng phải sử dụng nhiều tài nguyên tính toán.

Do đó, các kiểu dữ liệu có độ chính xác thấp hơn thường tính toán nhanh hơn nhưng phải hy sinh một số hiệu suất trên các chỉ số đánh giá như độ chính xác (tính toán nhanh hơn nhưng ít chính xác hơn).

> **Tài nguyên:** 
  * Xem [tài liệu PyTorch để biết danh sách tất cả các kiểu dữ liệu tensor có sẵn](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Đọc [trang Wikipedia để có cái nhìn tổng quan về độ chính xác trong điện toán là gì](https://en.wikipedia.org/wiki/Precision_(computer_science)).

Hãy xem cách tạo một số tensors với các kiểu dữ liệu cụ thể. Chúng ta có thể làm như vậy bằng cách sử dụng tham số `dtype`.

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Bên cạnh các vấn đề về hình dạng (hình dạng các tensor không khớp với nhau), hai trong số những vấn đề phổ biến khác mà bạn sẽ gặp phải trong PyTorch là các vấn đề về kiểu dữ liệu (datatype) và thiết bị (device).

Ví dụ, một trong các tensor là `torch.float32` và tensor kia là `torch.float16` (PyTorch thường muốn các tensor có cùng định dạng).

Hoặc một trong các tensor của bạn nằm trên CPU và tensor kia nằm trên GPU (PyTorch muốn các phép tính giữa các tensor được thực hiện trên cùng một thiết bị).

Chúng ta sẽ tìm hiểu thêm về thiết bị ở phần sau.

Bây giờ hãy tạo một tensor với `dtype=torch.float16`.

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Lấy thông tin từ tensors

Khi bạn đã tạo các tensors (hoặc một mô-đun PyTorch hay người khác đã tạo cho bạn), bạn có thể muốn lấy một số thông tin từ chúng.

Chúng ta đã thấy những điều này trước đây, nhưng ba thuộc tính phổ biến nhất mà bạn sẽ muốn tìm hiểu về tensors là:
* `shape` - tensor có hình dạng gì? (một số phép toán yêu cầu các quy tắc hình dạng cụ thể)
* `dtype` - các phần tử bên trong tensor được lưu trữ theo kiểu dữ liệu nào?
* `device` - tensor được lưu trữ trên thiết bị nào? (thường là GPU hoặc CPU)

Hãy tạo một tensor ngẫu nhiên và tìm hiểu thông tin chi tiết về nó.

In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8524, 0.8941, 0.5894, 0.7621],
        [0.4638, 0.4476, 0.6611, 0.9728],
        [0.9525, 0.0924, 0.9369, 0.1373]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


> **Lưu ý:** Khi bạn gặp sự cố trong PyTorch, rất thường là liên quan đến một trong ba thuộc tính trên. Vì vậy, khi các thông báo lỗi xuất hiện, hãy hát cho mình nghe một bài hát nhỏ có tên "cái gì, cái gì, ở đâu": 
  * "*tensors của tôi có hình dạng gì? kiểu dữ liệu của chúng là gì và chúng được lưu trữ ở đâu? hình dạng gì, kiểu dữ liệu gì, ở đâu ở đâu ở đâu*"

## Thao tác với tensors (các phép toán tensor)

Trong học sâu, dữ liệu (hình ảnh, văn bản, video, âm thanh, cấu trúc protein, v.v.) được biểu diễn dưới dạng các tensors.

Một mô hình học hỏi bằng cách xem xét các tensors đó và thực hiện một loạt các phép toán (có thể lên tới hàng triệu+) trên các tensors để tạo ra một biểu diễn các khuôn mẫu trong dữ liệu đầu vào.

Các phép toán này thường là sự kết hợp tuyệt vời giữa:
* Phép cộng (Addition)
* Phép trừ (Subtraction)
* Phép nhân (Multiplication - từng phần tử)
* Phép chia (Division)
* Phép nhân ma trận (Matrix multiplication)

V và chỉ có thế. Chắc chắn là có thêm một vài phép toán khác ở chỗ này hay chỗ kia, nhưng đây là những khối xây dựng cơ bản của mạng nơ-ron.

Bằng cách xếp chồng các khối xây dựng này theo đúng cách, bạn có thể tạo ra các mạng nơ-ron phức tạp nhất (giống như lego vậy!).

### Các phép toán cơ bản

Hãy bắt đầu với một vài phép toán cơ bản: phép cộng (`+`), phép trừ (`-`), phép nhân (`*`).

Chúng hoạt động đúng như bạn nghĩ.

In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Lưu ý rằng các giá trị tensor ở trên không biến thành `tensor([110, 120, 130])`, điều này là do các giá trị bên trong tensor không thay đổi trừ khi chúng được gán lại.

In [25]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

Hãy trừ đi một số và lần này chúng ta sẽ gán lại biến `tensor`.

In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch cũng có một loạt các hàm tích hợp sẵn như [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (viết tắt của phép nhân) và [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) để thực hiện các phép toán cơ bản.

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

Tuy nhiên, thông thường người ta sử dụng các ký hiệu toán tử như `*` thay vì `torch.mul()`

In [30]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Nhân ma trận (tất cả những gì bạn cần)

Một trong những phép toán phổ biến nhất trong các thuật toán học máy và học sâu (như mạng nơ-ron) là [nhân ma trận](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch triển khai chức năng nhân ma trận trong phương thức [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Hai quy tắc chính đối với phép nhân ma trận cần nhớ là:

1. Các **chiều bên trong (inner dimensions)** phải khớp nhau:
  * `(3, 2) @ (3, 2)` sẽ không hoạt động
  * `(2, 3) @ (3, 2)` sẽ hoạt động
  * `(3, 2) @ (2, 3)` sẽ hoạt động
2. Ma trận kết quả có hình dạng của các **chiều bên ngoài (outer dimensions)**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Lưu ý:** "`@`" trong Python là ký hiệu cho phép nhân ma trận.

> **Tài nguyên:** Bạn có thể xem tất cả các quy tắc cho phép nhân ma trận bằng `torch.matmul()` [trong tài liệu PyTorch](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Hãy tạo một tensor và thực hiện phép nhân từng phần tử cùng với phép nhân ma trận trên nó.

In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Sự khác biệt giữa nhân từng phần tử và nhân ma trận là việc cộng dồn các giá trị.

Đối với biến `tensor` của chúng ta có các giá trị `[1, 2, 3]`:

| Phép toán | Tính toán | Code |
| ----- | ----- | ----- |
| **Nhân từng phần tử (Element-wise multiplication)** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Nhân ma trận (Matrix multiplication)** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |

In [32]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

Bạn có thể thực hiện nhân ma trận bằng tay nhưng không nên.

Phương thức tích hợp `torch.matmul()` nhanh hơn nhiều.

In [35]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 695 µs, sys: 0 ns, total: 695 µs
Wall time: 537 µs


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 190 µs, sys: 0 ns, total: 190 µs
Wall time: 244 µs


tensor(14)

## Một trong những lỗi phổ biến nhất trong học sâu (lỗi hình dạng - shape errors)

Bởi vì phần lớn quá trình học sâu là nhân và thực hiện các phép toán trên ma trận và ma trận có một quy tắc nghiêm ngặt về hình dạng và kích thước nào có thể kết hợp với nhau, một trong những lỗi phổ biến nhất mà bạn sẽ gặp phải trong học sâu là hình dạng không khớp (shape mismatches).

In [37]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Chúng ta có thể làm cho phép nhân ma trận hoạt động giữa `tensor_A` và `tensor_B` bằng cách làm cho các chiều bên trong (inner dimensions) của chúng khớp nhau.

Một trong những cách để làm điều này là sử dụng phép **chuyển vị (transpose)** (hoán đổi các chiều của một tensor cho trước).

Bạn có thể thực hiện chuyển vị trong PyTorch bằng một trong hai cách:
* `torch.transpose(input, dim0, dim1)` - trong đó `input` là tensor mong muốn cần chuyển vị và `dim0`, `dim1` là các chiều sẽ được hoán đổi.
* `tensor.T` - trong đó `tensor` là tensor mong muốn cần chuyển vị.

Hãy thử cách thứ hai.

In [38]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Bạn cũng có thể sử dụng [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html), đây là dạng viết tắt của `torch.matmul()`.

In [41]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Nếu không có phép chuyển vị, các quy tắc của phép nhân ma trận không được thỏa mãn và chúng ta sẽ gặp lỗi như trên.

Cần một hình ảnh trực quan? 

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

Bạn có thể tạo các hình ảnh trực quan cho phép nhân ma trận của riêng mình như thế này tại http://matrixmultiplication.xyz/.

> **Lưu ý:** Một phép nhân ma trận như thế này cũng được gọi là [**tích vô hướng (dot product)**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) của hai ma trận.

Các mạng nơ-ron chứa đầy các phép nhân ma trận và tích vô hướng.

Mô-đun [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) (chúng ta sẽ thấy mô-đun này hoạt động ở phần sau), còn được gọi là lớp tiến thẳng (feed-forward layer) hay lớp kết nối đầy đủ (fully connected layer), triển khai một phép nhân ma trận giữa một đầu vào `x` và một ma trận trọng số `A`.

$$
y = x\cdot{A^T} + b
$$

Trong đó:
* `x` là đầu vào của lớp (học sâu là một ngăn xếp của các lớp như `torch.nn.Linear()` và các lớp khác xếp chồng lên nhau).
* `A` là ma trận trọng số (weights matrix) được tạo bởi lớp, bắt đầu là các số ngẫu nhiên sẽ được điều chỉnh khi mạng nơ-ron học cách biểu diễn tốt hơn các khuôn mẫu trong dữ liệu (lưu ý chữ "`T`", đó là vì ma trận trọng số được chuyển vị).
  * **Lưu ý:** Bạn cũng có thể thường xuyên thấy `W` hoặc một chữ cái khác như `X` được sử dụng để chỉ ma trận trọng số.
* `b` là hạng tử thiên vị (bias term) được sử dụng để bù trừ nhẹ cho các trọng số và đầu vào.
* `y` là đầu ra (sự thao tác của đầu vào với hy vọng khám phá ra các khuôn mẫu trong đó).

Đây là một hàm tuyến tính (linear function - bạn có thể đã thấy một thứ tương tự như $y = mx+b$ ở trường trung học hoặc nơi khác), và có thể được sử dụng để vẽ một đường thẳng!

Hãy chơi đùa một chút với lớp tuyến tính.

Thử thay đổi các giá trị của `in_features` và `out_features` bên dưới và xem điều gì xảy ra.

Bạn có nhận thấy điều gì liên quan đến hình dạng không?

In [42]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


> **Câu hỏi:** Điều gì xảy ra nếu bạn thay đổi `in_features` từ 2 thành 3 ở trên? Nó có báo lỗi không? Bạn có thể thay đổi hình dạng của đầu vào (`x`) như thế nào để xử lý lỗi đó? Gợi ý: chúng ta đã phải làm gì với `tensor_B` ở trên?

Nếu bạn chưa bao giờ làm điều đó trước đây, phép nhân ma trận có thể là một chủ đề khó hiểu lúc đầu.

Nhưng sau khi bạn đã chơi đùa với nó một vài lần và thậm chí là xem xét cấu trúc của một vài mạng nơ-ron, bạn sẽ nhận thấy nó ở khắp mọi nơi.

Hãy nhớ rằng, phép nhân ma trận là tất cả những gì bạn cần.

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*Khi bạn bắt đầu đào sâu vào các lớp của mạng nơ-ron và tự xây dựng các lớp của riêng mình, bạn sẽ thấy phép nhân ma trận ở khắp mọi nơi. **Nguồn:** https://marksaroufim.substack.com/p/working-class-deep-learner*

### Tìm giá trị nhỏ nhất (min), lớn nhất (max), trung bình (mean), tổng (sum), v.v. (tổng hợp - aggregation)

Bây giờ chúng ta đã thấy một vài cách thao tác trên tensor, hãy điểm qua một số cách để tổng hợp chúng (chuyển từ nhiều giá trị xuống ít giá trị hơn).

Đầu tiên, chúng ta sẽ tạo một tensor và sau đó tìm giá trị lớn nhất, nhỏ nhất, trung bình và tổng của nó.

In [43]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Bây giờ hãy thực hiện một số phép tổng hợp.

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Lưu ý:** Bạn có thể thấy một số phương thức như `torch.mean()` yêu cầu tensor phải ở định dạng `torch.float32` (phổ biến nhất) hoặc một kiểu dữ liệu cụ thể khác, nếu không phép toán sẽ không thành công. 

Bạn cũng có thể làm tương tự như trên với các phương thức `torch`.

In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Vị trí min/max (Positional min/max)

Bạn cũng có thể tìm chỉ mục (index) của tensor nơi xảy ra giá trị max hoặc min lần lượt bằng [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) và [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html).

Điều này rất hữu ích trong trường hợp bạn chỉ muốn biết vị trí (position) nơi chứa giá trị cao nhất (hoặc thấp nhất) chứ không phải giá trị thực tế đó là bao nhiêu (chúng ta sẽ thấy điều này ở phần sau khi sử dụng [hàm kích hoạt softmax](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [46]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Thay đổi kiểu dữ liệu của tensor

Như đã đề cập, một vấn đề phổ biến đối với các phép toán học sâu là việc các tensors của bạn có kiểu dữ liệu khác nhau.

Nếu một tensor ở định dạng `torch.float64` và một tensor khác ở định dạng `torch.float32`, bạn có thể gặp phải một số lỗi.

Nhưng có một cách khắc phục.

Bạn có thể thay đổi kiểu dữ liệu của tensors bằng cách sử dụng [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) trong đó tham số `dtype` là kiểu dữ liệu bạn muốn sử dụng.

Đầu tiên chúng ta sẽ tạo một tensor và kiểm tra kiểu dữ liệu của nó (mặc định là `torch.float32`).

In [47]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

Bây giờ chúng ta sẽ tạo một tensor khác giống như trước nhưng thay đổi kiểu dữ liệu của nó thành `torch.float16`.

In [48]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Và chúng ta có thể làm điều tương tự để tạo một tensor `torch.int8`.

In [49]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Lưu ý:** Các kiểu dữ liệu khác nhau có thể gây nhầm lẫn khi mới bắt đầu. Nhưng hãy nghĩ theo cách này, số càng thấp (ví dụ: 32, 16, 8), máy tính càng lưu trữ giá trị với ít độ chính xác hơn. Và với dung lượng lưu trữ ít hơn, điều này thường dẫn đến tốc độ tính toán nhanh hơn và một mô hình tổng thể nhỏ hơn. Các mạng nơ-ron trên thiết bị di động thường hoạt động với các số nguyên 8-bit, nhỏ hơn và chạy nhanh hơn nhưng kém chính xác hơn so với các đối tác float32 của chúng. Để biết thêm về điều này, tôi khuyên bạn nên đọc về [độ chính xác trong điện toán (precision in computing)](https://en.wikipedia.org/wiki/Precision_(computer_science)).
>
> **Bài tập:** Cho đến nay chúng ta đã đề cập khá nhiều phương thức tensor nhưng còn rất nhiều phương thức khác trong [tài liệu `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html), tôi khuyên bạn nên dành 10 phút cuộn qua và tìm hiểu bất kỳ phương thức nào thu hút sự chú ý của bạn. Nhấp vào chúng và sau đó tự viết chúng thành mã để xem điều gì xảy ra.

### Định hình lại (Reshaping), xếp chồng (stacking), ép (squeezing) và giãn (unsqueezing)

Thường thì bạn sẽ muốn định hình lại (reshape) hoặc thay đổi số chiều của tensor mà không thực sự thay đổi các giá trị bên trong chúng.

Để làm như vậy, một số phương thức phổ biến là:

| Phương thức | Mô tả ngắn gọn |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Định hình lại `input` theo `shape` (nếu tương thích), cũng có thể sử dụng `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Trả về một góc nhìn (view) của tensor gốc theo một `shape` khác nhưng chia sẻ cùng một dữ liệu với tensor gốc. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Nối một chuỗi các `tensors` dọc theo một chiều mới (`dim`), tất cả `tensors` phải có cùng kích thước. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Ép `input` để loại bỏ tất cả các chiều có giá trị là `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Trả về `input` với một chiều có giá trị là `1` được thêm vào tại `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Trả về một *góc nhìn (view)* của `input` ban đầu với các chiều của nó được hoán vị (sắp xếp lại) theo `dims`. | 

Tại sao lại làm bất kỳ điều nào trong số này?

Bởi vì các mô hình học sâu (mạng nơ-ron) hoàn toàn xoay quanh việc thao tác các tensor theo cách nào đó. Và do các quy tắc của phép nhân ma trận, nếu bạn gặp phải sự không khớp về hình dạng, bạn sẽ gặp lỗi. Các phương thức này giúp bạn đảm bảo rằng các phần tử thích hợp của tensor đang kết hợp với các phần tử thích hợp của các tensor khác. 

Hãy thử nghiệm chúng.

Đầu tiên, chúng ta sẽ tạo một tensor.

In [50]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Bây giờ hãy thêm một chiều nữa bằng `torch.reshape()`.

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Chúng ta cũng có thể thay đổi góc nhìn với `torch.view()`.

In [52]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Tuy nhiên, hãy nhớ rằng việc thay đổi góc nhìn của một tensor bằng `torch.view()` thực sự chỉ tạo ra một góc nhìn mới của *cùng* một tensor.

Vì vậy, việc thay đổi góc nhìn cũng làm thay đổi luôn tensor ban đầu.

In [53]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Nếu chúng ta muốn xếp chồng tensor mới của mình lên chính nó năm lần, chúng ta có thể làm như vậy với `torch.stack()`.

In [54]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Còn việc xóa tất cả các chiều có giá trị là 1 khỏi một tensor thì sao?

Để làm điều đó, bạn có thể sử dụng `torch.squeeze()` (tôi nhớ điều này như việc *ép* (squeeze) tensor lại để nó chỉ còn các chiều lớn hơn 1).

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Và để thực hiện ngược lại với `torch.squeeze()`, bạn có thể sử dụng `torch.unsqueeze()` để thêm một chiều có giá trị là 1 vào một chỉ mục cụ thể.

In [56]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


Bạn cũng có thể sắp xếp lại thứ tự của các trục bằng `torch.permute(input, dims)`, trong đó `input` được chuyển thành một *góc nhìn (view)* với các `dims` mới.

In [57]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **Lưu ý**: Bởi vì việc hoán vị trả về một *góc nhìn (view)* (chia sẻ cùng dữ liệu với tensor gốc), các giá trị trong tensor được hoán vị sẽ giống với tensor gốc và nếu bạn thay đổi các giá trị trong góc nhìn, nó sẽ làm thay đổi các giá trị của tensor gốc.

## Lập chỉ mục (chọn dữ liệu từ tensors)

Đôi khi bạn sẽ muốn chọn dữ liệu cụ thể từ các tensors (ví dụ: chỉ lấy cột đầu tiên hoặc hàng thứ hai).

Để làm điều đó, bạn có thể sử dụng lập chỉ mục (indexing).

Nếu bạn đã từng lập chỉ mục trên danh sách Python hoặc mảng NumPy, thì lập chỉ mục trong PyTorch với các tensors cũng rất tương tự.

In [58]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Lập chỉ mục các giá trị diễn ra từ chiều ngoài vào chiều trong (hãy xem các dấu ngoặc vuông).

In [59]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Bạn cũng có thể sử dụng `:` để chỉ định "tất cả các giá trị trong chiều này" và sau đó sử dụng dấu phẩy (`,`) để thêm một chiều khác.

In [60]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Lập chỉ mục có thể khá khó hiểu lúc ban đầu, đặc biệt là với các tensors lớn (tôi vẫn phải thử lập chỉ mục nhiều lần mới làm đúng được). Nhưng với một chút thực hành và làm theo phương châm của nhà thám hiểm dữ liệu (***trực quan hóa, trực quan hóa, trực quan hóa***), bạn sẽ dần bắt nhịp được.

## PyTorch tensors & NumPy

Vì NumPy là một thư viện điện toán số học phổ biến của Python, PyTorch có chức năng tương tác rất tốt với nó.  

Hai phương thức chính bạn sẽ muốn sử dụng để chuyển từ NumPy sang PyTorch (và ngược lại) là: 
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - Mảng NumPy -> Tensor PyTorch. 
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - Tensor PyTorch -> Mảng NumPy.

Hãy thử xem.

In [65]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Lưu ý:** Theo mặc định, các mảng NumPy được tạo với kiểu dữ liệu `float64` và nếu bạn chuyển đổi nó thành một tensor PyTorch, nó sẽ giữ nguyên kiểu dữ liệu (như ở trên). 
>
> Tuy nhiên, nhiều phép tính của PyTorch mặc định sử dụng `float32`. 
> 
> Vì vậy, nếu bạn muốn chuyển đổi mảng NumPy (float64) -> tensor PyTorch (float64) -> tensor PyTorch (float32), bạn có thể sử dụng `tensor = torch.from_numpy(array).type(torch.float32)`.

Bởi vì chúng ta đã gán lại `tensor` ở trên, nếu bạn thay đổi tensor, mảng vẫn giữ nguyên.

In [66]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Và nếu bạn muốn chuyển từ tensor PyTorch sang mảng NumPy, bạn có thể gọi `tensor.numpy()`.

In [67]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Và quy tắc tương tự như trên cũng được áp dụng, nếu bạn thay đổi `tensor` gốc, `numpy_tensor` mới vẫn giữ nguyên.

In [64]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Tính tái lập (cố gắng loại bỏ tính ngẫu nhiên)

Khi bạn tìm hiểu thêm về mạng nơ-ron và học máy, bạn sẽ bắt đầu khám phá ra mức độ ảnh hưởng của sự ngẫu nhiên.

À, đó là sự giả ngẫu nhiên (pseudorandomness). Bởi vì suy cho cùng, theo thiết kế, một máy tính về cơ bản là mang tính quyết định (deterministic - mỗi bước đều có thể dự đoán được) nên sự ngẫu nhiên mà chúng tạo ra là sự ngẫu nhiên được mô phỏng (mặc dù cũng có tranh luận về điều này, nhưng vì tôi không phải là một nhà khoa học máy tính, tôi sẽ để bạn tự tìm hiểu thêm).

Vậy điều này liên quan thế nào đến mạng nơ-ron và học sâu?

Chúng ta đã thảo luận rằng các mạng nơ-ron bắt đầu với các số ngẫu nhiên để mô tả các khuôn mẫu trong dữ liệu (những con số này là những mô tả kém) và cố gắng cải thiện những con số ngẫu nhiên đó bằng cách sử dụng các phép toán tensor (và một vài thứ khác mà chúng ta chưa thảo luận) để mô tả tốt hơn các khuôn mẫu trong dữ liệu.

Tóm lại: 

`bắt đầu với các số ngẫu nhiên -> các phép toán tensor -> cố gắng làm cho tốt hơn (lặp đi lặp lại)`

Mặc dù sự ngẫu nhiên rất tốt và mạnh mẽ, nhưng đôi khi bạn muốn bớt đi một chút sự ngẫu nhiên.

Tại sao?

Để bạn có thể thực hiện các thí nghiệm có thể lặp lại (repeatable experiments).

Ví dụ, bạn tạo ra một thuật toán có khả năng đạt được hiệu suất X.

Và sau đó bạn của bạn dùng thử nó để xác minh rằng bạn không hề điên.

Làm thế nào họ có thể làm được như vậy?

Đó là lúc **tính tái lập (reproducibility)** phát huy tác dụng.

Nói cách khác, bạn có thể nhận được kết quả tương tự (hoặc rất giống) trên máy tính của mình khi chạy cùng một đoạn mã như tôi nhận được trên máy tính của tôi không?

Hãy xem một ví dụ ngắn về tính tái lập trong PyTorch.

Chúng ta sẽ bắt đầu bằng cách tạo hai tensors ngẫu nhiên, vì chúng ngẫu nhiên, bạn sẽ hy vọng chúng khác nhau đúng không?

In [68]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Đúng như bạn có thể mong đợi, các tensors ra kết quả với các giá trị khác nhau.

Nhưng nếu bạn muốn tạo hai tensors ngẫu nhiên với *cùng* giá trị thì sao.

Nghĩa là, các tensors vẫn chứa các giá trị ngẫu nhiên nhưng chúng sẽ có cùng một hương vị (flavour).

Đó là lúc [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) xuất hiện, trong đó `seed` là một số nguyên (như `42` nhưng có thể là bất cứ số nào) để tạo ra "hương vị" cho sự ngẫu nhiên.

Hãy thử bằng cách tạo một số tensors ngẫu nhiên *có hương vị*.

In [69]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Tuyệt quá!

Có vẻ như việc thiết lập seed đã hoạt động. 

> **Tài nguyên:** Những gì chúng ta vừa đề cập chỉ là bề nổi của tính tái lập trong PyTorch. Để biết thêm về tính tái lập nói chung và các random seeds, tôi khuyên bạn nên xem:
> * [Tài liệu về tính tái lập của PyTorch](https://pytorch.org/docs/stable/notes/randomness.html) (một bài tập tốt là đọc lướt qua phần này trong 10 phút, và ngay cả khi bạn không hiểu nó bây giờ, việc nhận thức được nó vẫn rất quan trọng).
> * [Trang Wikipedia về random seed](https://en.wikipedia.org/wiki/Random_seed) (điều này sẽ cung cấp một cái nhìn tổng quan tốt về các random seeds và sự giả ngẫu nhiên nói chung).

## Chạy tensors trên GPU (và thực hiện tính toán nhanh hơn)

Các thuật toán học sâu yêu cầu rất nhiều phép toán số học.

Và theo mặc định, những phép toán này thường được thực hiện trên CPU (đơn vị xử lý trung tâm).

Tuy nhiên, có một phần cứng phổ biến khác gọi là GPU (đơn vị xử lý đồ họa), thường thực hiện nhanh hơn nhiều các loại phép toán cụ thể mà mạng nơ-ron cần (phép nhân ma trận) so với CPU.

Máy tính của bạn có thể có một cái.

Nếu có, bạn nên tìm cách sử dụng nó bất cứ khi nào có thể để huấn luyện các mạng nơ-ron, bởi vì rất có thể nó sẽ tăng tốc đáng kể thời gian huấn luyện.

Có một vài cách để trước tiên tiếp cận được với một GPU và sau đó làm cho PyTorch sử dụng GPU đó.

> **Lưu ý:** Khi tôi đề cập đến "GPU" trong suốt khóa học này, tôi đang nói đến một [GPU của Nvidia có hỗ trợ CUDA](https://developer.nvidia.com/cuda-gpus) (CUDA là một nền tảng điện toán và API giúp cho phép các GPU được sử dụng cho tính toán đa dụng chứ không chỉ riêng đồ họa) trừ khi được chỉ định khác.

### 1. Lấy một GPU

Bạn có thể đã biết những gì đang diễn ra khi tôi nói về GPU. Nhưng nếu không, có một vài cách để tiếp cận một chiếc.

| **Phương pháp** | **Mức độ khó thiết lập** | **Ưu điểm** | **Nhược điểm** | **Cách thiết lập** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Dễ | Miễn phí sử dụng, gần như không cần thiết lập, có thể chia sẻ công việc với người khác dễ dàng qua một liên kết | Không lưu dữ liệu đầu ra của bạn, giới hạn tính toán, dễ bị ngắt kết nối | [Làm theo Hướng dẫn Google Colab](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Sử dụng máy của bạn | Trung bình | Chạy mọi thứ cục bộ trên máy của riêng bạn | Các GPU không miễn phí, yêu cầu chi phí trả trước | Làm theo [các nguyên tắc cài đặt PyTorch](https://pytorch.org/get-started/locally/) |
| Điện toán đám mây (AWS, GCP, Azure) | Trung bình-Khó | Chi phí trả trước nhỏ, có thể tiếp cận tài nguyên điện toán gần như vô hạn | Có thể trở nên đắt đỏ nếu chạy liên tục, mất một chút thời gian để thiết lập đúng cách | Làm theo [các nguyên tắc cài đặt PyTorch](https://pytorch.org/get-started/cloud-partners/) |

Có nhiều tùy chọn khác để sử dụng GPU nhưng 3 phương pháp trên là đủ cho bây giờ.

Cá nhân tôi sử dụng kết hợp giữa Google Colab và máy tính cá nhân của mình cho các thử nghiệm quy mô nhỏ (và việc tạo ra khóa học này) và chuyển sang tài nguyên đám mây khi cần nhiều sức mạnh tính toán hơn.

> **Tài nguyên:** Nếu bạn đang tìm mua một GPU cho riêng mình nhưng không chắc nên chọn loại nào, [Tim Dettmers có một hướng dẫn tuyệt vời](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

Để kiểm tra xem bạn có quyền truy cập vào GPU Nvidia hay không, bạn có thể chạy `!nvidia-smi` trong đó `!` (còn gọi là dấu chấm than) có nghĩa là "chạy lệnh này trên dòng lệnh (command line)".

In [70]:
!nvidia-smi

Fri Nov  1 08:25:53 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
|  0%   38C    P2             82W /  480W |   13068MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Nếu bạn không có GPU Nvidia nào có thể truy cập được, mã trên sẽ xuất ra thứ gì đó giống như:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

Trong trường hợp đó, hãy quay lại và làm theo các bước cài đặt.

Nếu bạn có GPU, dòng trên sẽ xuất ra thứ gì đó giống như:

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

### 2. Thiết lập để PyTorch chạy trên GPU

Khi bạn đã có một GPU sẵn sàng để truy cập, bước tiếp theo là thiết lập PyTorch sử dụng nó để lưu trữ dữ liệu (tensors) và tính toán dữ liệu (thực hiện các phép toán trên tensors).

Để làm vậy, bạn có thể sử dụng gói (package) [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html).

Thay vì nói về nó, chúng ta hãy thử xem sao.

Bạn có thể kiểm tra xem PyTorch có quyền truy cập vào GPU hay không bằng cách sử dụng [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).

In [71]:
# Check for GPU
import torch
torch.cuda.is_available()

True

Nếu kết quả ở trên là `True`, PyTorch có thể thấy và sử dụng GPU, nếu nó trả về `False`, nó không thể thấy GPU và trong trường hợp đó, bạn sẽ phải làm lại các bước cài đặt.

Bây giờ, giả sử bạn muốn thiết lập đoạn mã của mình để nó chạy trên CPU *hoặc* trên GPU nếu có sẵn.

Bằng cách đó, nếu bạn hoặc ai đó quyết định chạy đoạn mã của bạn, nó sẽ hoạt động bất kể thiết bị tính toán mà họ đang sử dụng là gì. 

Hãy tạo một biến `device` để lưu trữ loại thiết bị nào đang khả dụng.

In [72]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Nếu kết quả ở trên là `"cuda"`, điều đó có nghĩa là chúng ta có thể thiết lập toàn bộ mã PyTorch của mình sử dụng thiết bị CUDA khả dụng (một GPU) và nếu nó trả về `"cpu"`, mã PyTorch của chúng ta sẽ sử dụng CPU.

> **Lưu ý:** Trong PyTorch, phương pháp tốt nhất là viết [**mã không phụ thuộc thiết bị (device agnostic code)**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). Điều này có nghĩa là mã sẽ chạy trên CPU (luôn có sẵn) hoặc GPU (nếu có).

Nếu bạn muốn thực hiện tính toán nhanh hơn, bạn có thể sử dụng một GPU, nhưng nếu bạn muốn tính toán *nhanh hơn rất nhiều*, bạn có thể sử dụng nhiều GPU.

Bạn có thể đếm số lượng GPU mà PyTorch có quyền truy cập bằng cách sử dụng [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [73]:
# Count number of devices
torch.cuda.device_count()

1

Biết được số lượng GPU mà PyTorch có thể truy cập rất hữu ích trong trường hợp bạn muốn chạy một quá trình cụ thể trên một GPU và một quá trình khác trên một GPU khác (PyTorch cũng có các tính năng cho phép bạn chạy một quá trình trên *tất cả* các GPU).

### 2.1 Chạy PyTorch trên Apple Silicon

Để chạy PyTorch trên các GPU M1/M2/M3 của Apple, bạn có thể sử dụng mô-đun [`torch.backends.mps`](https://pytorch.org/docs/stable/notes/mps.html).

Đảm bảo rằng các phiên bản macOS và PyTorch đã được cập nhật.

Bạn có thể kiểm tra xem PyTorch có quyền truy cập vào GPU hay không bằng cách sử dụng `torch.backends.mps.is_available()`.

In [74]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [75]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

Tương tự như trước, nếu mã ở trên trả về `"mps"`, điều đó có nghĩa là chúng ta có thể thiết lập toàn bộ mã PyTorch của mình để sử dụng GPU Apple Silicon có sẵn.

In [76]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

### 3. Đưa tensors (và các mô hình) vào GPU

Bạn có thể đưa tensors (và các mô hình, chúng ta sẽ thấy ở phần sau) vào một thiết bị cụ thể bằng cách gọi [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) trên chúng. Trong đó `device` là thiết bị mục tiêu mà bạn muốn đưa tensor (hoặc mô hình) vào.

Tại sao phải làm việc này?

GPU cung cấp tốc độ tính toán số học nhanh hơn nhiều so với CPU và nếu không có GPU, nhờ vào mã không phụ thuộc thiết bị (device agnostic code - xem ở trên) của chúng ta, nó sẽ chạy trên CPU.

> **Lưu ý:** Đưa một tensor vào GPU bằng `to(device)` (ví dụ: `some_tensor.to(device)`) sẽ trả về một bản sao của tensor đó, ví dụ: cùng một tensor sẽ nằm trên cả CPU và GPU. Để ghi đè lên các tensors, hãy gán lại chúng:
>
> `some_tensor = some_tensor.to(device)`

Hãy thử tạo một tensor và đưa nó vào GPU (nếu có sẵn).

In [77]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Nếu bạn có một GPU khả dụng, đoạn mã trên sẽ xuất ra thứ gì đó giống như:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

Lưu ý rằng tensor thứ hai có `device='cuda:0'`, điều này có nghĩa là nó được lưu trữ trên GPU thứ 0 có sẵn (các GPU được lập chỉ mục từ 0, nếu có hai GPU có sẵn, chúng sẽ lần lượt là `'cuda:0'` và `'cuda:1'`, lên tới `'cuda:n'`).

### 4. Đưa tensors trở lại CPU

Điều gì sẽ xảy ra nếu chúng ta muốn đưa tensor trở lại CPU?

Ví dụ: bạn sẽ muốn làm điều này nếu bạn muốn tương tác với các tensors của mình bằng NumPy (NumPy không tận dụng được GPU).

Hãy thử sử dụng phương thức [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) trên biến `tensor_on_gpu` của chúng ta.

In [78]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Thay vào đó, để đưa một tensor về lại CPU và có thể sử dụng được với NumPy, chúng ta có thể sử dụng [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

Thao tác này sẽ sao chép tensor vào bộ nhớ của CPU để nó có thể được sử dụng với các CPU.

In [79]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Đoạn mã trên trả về một bản sao của tensor GPU trong bộ nhớ CPU, do đó tensor ban đầu vẫn nằm trên GPU.

In [77]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Bài tập

Tất cả các bài tập đều tập trung vào việc thực hành những đoạn mã ở trên.

Bạn sẽ có thể hoàn thành chúng bằng cách tham khảo từng phần hoặc làm theo (các) tài liệu tham khảo được liên kết.

**Tài nguyên:**

* [Notebook bài tập mẫu cho phần 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Notebook giải pháp mẫu cho phần 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (hãy tự làm các bài tập *trước khi* xem phần này).

1. Đọc tài liệu - Một phần lớn của học sâu (và việc học code nói chung) là làm quen với tài liệu của một framework cụ thể mà bạn đang sử dụng. Chúng ta sẽ sử dụng tài liệu PyTorch rất nhiều trong phần còn lại của khóa học này. Vì vậy, tôi khuyên bạn nên dành 10 phút để đọc các phần sau (không sao cả nếu bây giờ bạn không hiểu một số thứ, mục tiêu hiện tại chưa phải là hiểu toàn bộ, mà là nhận biết). Hãy xem tài liệu về [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) và [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Tạo một random tensor (tensor ngẫu nhiên) có hình dạng `(7, 7)`.
3. Thực hiện phép nhân ma trận trên tensor từ câu 2 với một random tensor khác có hình dạng `(1, 7)` (gợi ý: bạn có thể phải chuyển vị tensor thứ hai).
4. Đặt random seed (hạt giống ngẫu nhiên) thành `0` và thực hiện lại các bài tập 2 & 3.
5. Nói về random seed, chúng ta đã thấy cách thiết lập nó với `torch.manual_seed()` nhưng có tính năng tương đương nào cho GPU không? (gợi ý: bạn sẽ cần tìm trong tài liệu của `torch.cuda` cho câu này). Nếu có, hãy đặt random seed của GPU thành `1234`.
6. Tạo hai random tensors có hình dạng `(2, 3)` và gửi cả hai vào GPU (bạn sẽ cần quyền truy cập vào một GPU cho bài này). Thiết lập `torch.manual_seed(1234)` khi tạo các tensors (đây không nhất thiết phải là random seed của GPU).
7. Thực hiện phép nhân ma trận trên các tensors bạn vừa tạo ở câu 6 (một lần nữa, bạn có thể phải điều chỉnh hình dạng của một trong các tensors).
8. Tìm các giá trị lớn nhất (maximum) và nhỏ nhất (minimum) của đầu ra từ câu 7.
9. Tìm các chỉ mục chứa giá trị lớn nhất và nhỏ nhất của đầu ra từ câu 7.
10. Tạo một random tensor có hình dạng `(1, 1, 1, 10)` và sau đó tạo một tensor mới với tất cả các chiều có giá trị `1` bị loại bỏ để chỉ còn lại một tensor có hình dạng `(10)`. Thiết lập seed thành `7` khi bạn tạo nó và in ra tensor đầu tiên cùng với hình dạng của nó cũng như tensor thứ hai cùng với hình dạng của nó.

## Bổ sung ngoài chương trình

* Dành 1 giờ để xem qua [hướng dẫn cơ bản về PyTorch](https://pytorch.org/tutorials/beginner/basics/intro.html) (Tôi khuyên bạn nên xem các phần [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) và [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)).
* Để tìm hiểu thêm về cách một tensor có thể biểu diễn dữ liệu, hãy xem video này: [What's a tensor?](https://youtu.be/f5liqUk0ZTw)